@startuml aliu

participant "前端" as Frontend
participant "操作层主控端" as OperationModule

Frontend -> OperationModule: 请求项目文件目录
OperationModule --> Frontend: 返回项目文件目录

group 管理层初始化
    group 策略管理器初始化
        Frontend -> OperationModule: 请求策略注册表
        OperationModule --> Frontend: 发送策略注册表
    end
    group 配置管理器初始化
        Frontend -> OperationModule: 发送配置文件路径
        OperationModule --> Frontend: 发送配置表单

        opt 用户修改配置
            Frontend -> OperationModule: 发送修改后的配置表单
            alt 用户选择保存配置文件
            else 用户选择覆盖配置文件
            end
        end
    end
    group 资源管理器初始化
        alt 配置文件不包含资源文件路径
            Frontend -> OperationModule: 发送资源文件路径
        end
    end
end
opt 前端请求同步配置表单
    Frontend -> OperationModule: 请求同步配置表单
    OperationModule --> Frontend: 发送配置表单
end
opt 用户预览数据
    Frontend -> OperationModule: 发送数据文件路径

    alt 用户选择渲染策略
        Frontend -> OperationModule: 发送渲染策略
        OperationModule --> Frontend: 发送渲染结果
    else 使用前端框架原生渲染策略
        OperationModule --> Frontend: 发送数据
    end
end
group 数据预处理
    Frontend --> Frontend: 记录预处理策略队列

    Frontend -> OperationModule: 查询预处理数据文件目录

    OperationModule --> Frontend: 返回预处理数据文件目录
    opt 用户修改预处理文件目录
        Frontend -> OperationModule: 发送预处理数据文件目录
        OperationModule --> Frontend: 返回预处理数据文件目录
    end

    Frontend -> OperationModule: 发送预处理策略队列
    loop 数据预处理
        alt 用户选择保存结果
        else 用户选择不保存结果
            
            alt 用户选择渲染策略
                Frontend -> OperationModule: 发送渲染策略
                OperationModule --> Frontend: 发送渲染结果
            else 使用前端框架原生渲染策略
                OperationModule --> Frontend: 发送预处理结果
            end
        end
        OperationModule --> Frontend: 发送预处理信息
    end
end
group 模型训练
    Frontend -> OperationModule: 查询训练数据目录
    OperationModule --> Frontend: 返回训练数据目录
    opt 用户修改训练数据目录
        Frontend -> OperationModule: 发送训练数据目录
        OperationModule --> Frontend: 返回训练数据目录
    end
    Frontend -> OperationModule: 发送模型训练策略执行请求


    alt 用户选择模型资源文件
        Frontend -> OperationModule: 发送模型资源文件路径
    end

    loop 模型训练
        OperationModule --> Frontend: 发送训练信息
    end
end

group 模型推理
    opt 用户选择模型资源文件
        Frontend -> OperationModule: 发送模型资源文件路径
    end
    Frontend -> OperationModule: 查询推理数据目录
    OperationModule --> Frontend: 返回推理数据目录
    opt 用户修改推理数据目录
        Frontend -> OperationModule: 发送推理数据目录
        OperationModule --> Frontend: 返回推理数据目录
    end
    Frontend -> OperationModule: 请求执行推理策略
    loop 模型推理
        opt 用户预览推理结果
            alt 用户选择渲染策略
                Frontend -> OperationModule: 发送渲染策略
                OperationModule --> Frontend: 发送渲染结果
            else 使用前端框架原生渲染策略
                OperationModule --> Frontend: 发送数据
            end
        end
        OperationModule --> Frontend: 发送推理信息
    end 
end
@enduml
