openapi: 3.1.0
info:
  title: OperationEnd API
  version: 0.9.8
  description: 系统OperationEnd组件的API

servers:
  - url: https://api.operationend.我是占位符.com/v1

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '200':
          description: 注册成功
        '400':
          description: 无效输入

  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: 无效凭证

  /file/strategy:
    get:
      tags:
        - 同步
      summary: 请求同步策略注册表
      security:
        - bearerAuth: ['read']
      parameters:
      - name: project_name
        required: true
        schema:
            type: string
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StrategyRegistryResponse'
        '501':
          description: ErrorResponse
  /file/directory:
    get:
      tags:
        - 同步
      summary: 请求同步项目文件目录
      security:
        - bearerAuth: ['read']
      parameters:
      - name: project_name
        required: true
        schema:
            type: string
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectoryResponse'
        '501':
          description: ErrorResponse
  /file/project-list:
    get:
      tags:
        - 同步
      summary: 请求项目列表
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectListResponse'
        '501':
          description: ErrorResponse
  /file/config:
    get:
      tags:
        - 配置
      summary: 请求同步配置文件
      security:
        - bearerAuth: ['read']
      parameters:
      - name: project_name
        required: true
        schema:
            type: string
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationResponse'
        '501':
          description: ErrorResponse
    put:
      tags:
        - 配置
      summary: 发送修改后的配置表单
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ConfigurationRequest'
      responses:
        '200':
          description: SuccessResponse
        '500':
          description: ErrorResponse
    post:
      tags:
        - 配置
      summary: 修改配置文件路径
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                file_path:
                  type: string
                  description: 文件路径
      responses:
        '200':
          description: SuccessResponse
        '500':
          description: ErrorResponse

  /file:
    parameters:
      - name: file_path
        in: query
        required: true
        schema:
          type: string
        description: 文件路径
    post:
      tags:
        - 文件操作
      summary: 创建文件或文件夹
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileCreationRequest'
      responses:
        '200':
          description: SuccessResponse
        '500':
          description: ErrorResponse
    put:
      tags:
        - 文件操作
      summary: 修改文件内容
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileModificationRequest'
      responses:
        '200':
          description: SuccessResponse
        '501':
          description: ErrorResponse
        '500':
          description: ErrorResponse
    get:
      tags:
        - 文件操作
      summary: 查看文件内容
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 成功获取文件内容
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileContentResponse'
        '404':
          description: NotFoundResponse
        '500':
          description: ErrorResponse
    patch:
      tags:
        - 文件操作
      summary: 重命名用户文件
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: 新文件名
      responses:
        '200':
          description: SuccessResponse
        '500':
          description: ErrorResponse
    delete:
      tags:
        - 文件操作
      summary: 删除用户文件
      security:
        - bearerAuth: ['write']
      responses:
        '200':
          description: SuccessResponse
        '500':
          description: ErrorResponse
  /mission:
    get:
      tags:
        - 任务管理
      summary: 通过 WebSocket 连接获取任务状态
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 成功获取任务状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionStatusResponse'
        '500':
          description: ErrorResponse
    post:
      tags:
        - 任务管理
      summary: 通过 WebSocket 连接发送任务信息
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MissionRequest'
      responses:
        '200':
          description: 成功发送任务信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionResponse'
        '500':
          description: ErrorResponse
    delete:
      tags:
        - 任务管理
      summary: 停止运行中的任务或删除等待中的任务
      security:
        - bearerAuth: ['write']
      parameters:
        - in: query
          name: mission_name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: SuccessResponse
        '500':
          description: ErrorResponse
  /monitor:
    get:
      tags:
        - 系统监控
      summary: 获取系统状态信息（允许空值）
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 成功获取系统状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatusResponse'
        '500':
          description: ErrorResponse

  /scene/{sceneId}:
    parameters:
      - in: path
        name: sceneId
        required: true
        schema:
          type: string
    post:
      summary: Save current scene
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectScene'
      responses:
        '200':
          description: 场景保存成功
    get:
      summary: Restore project scene
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectScene'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      flows:
        authorizationCode:
          authorizationUrl: https://auth.operationend.我是占位符.com/oauth/authorize
          tokenUrl: https://auth.operationend.我是占位符.com/oauth/token
          scopes:
            read: 读权
            write: 写权

  schemas:
    UserRegistration:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string

    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    AuthToken:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer

    StrategyRegistryResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            strategy_registry:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/StrategyInfo'
    StrategyInfo:
      type: object
      properties:
        argus:
          type: object
          properties:
            argu_name:
              type: string
            argu_annotation:
              type: string
            argu_default:
              type: string
        return_annotation:
          type: string
        comment:
          type: string
    ConfigurationResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            configuration:
              type: object
              additionalProperties: true
    DirectoryResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            file_directory:
              type: object
              additionalProperties:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: object
    ProjectListResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            project_list:
              type: array
              items:
                type: string
    ConfigurationRequest:
      type: object
      properties:
        project_name:
          type: string
        content:
          type: object
          additionalProperties: true
    FileCreationRequest:
      type: object
      properties:
        path:
          type: string
    FileModificationRequest:
      type: object
      properties:
        file_path:
          type: string
          description: 文件路径
        content:
          type: string
          description: 文件内容
    FileContentResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            content:
              type: string
    MissionStatusResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          additionalProperties:
            type: object
    MissionRequest:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: object
          properties:
            STRATEGY_QUEUE:
              type: array
              items:
                type: object
                required: [ID, FUNC, ARGS]
                properties:
                  ID:
                    type: string
                  FUNC:
                    type: string
                  ARGS:
                    type: object
                    additionalProperties: 
                      type: string
            ITER:
              type: boolean
            GET_OUTPUT:
              type: array
              items:
                type: string
    MissionResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          additionalProperties:
            type: object
    SystemStatusResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            CPU:
              type: object
              properties:
                load:
                  type: string
                temperature:
                  type: string
                power:
                  type: string
            RAM:
              type: object
              properties:
                load:
                  type: string
            GPU:
              type: object
              properties:
                load:
                  type: string
                temperature:
                  type: string
                power:
                  type: string
            HDD:
              type: object
              properties:
                load:
                  type: string
