openapi: 3.1.0
info:
  title: OperationEnd API
  version: 0.9.5
  description: API for the OperationEnd component of the system

servers:
  - url: https://api.operationend.我是占位符.com/v1

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '200':
          description: Successful registration
        '400':
          description: Invalid input

  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Invalid credentials

  /sync/file/strategy:
    get:
      tags:
        - 同步
      summary: 请求同步策略注册表
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      strategy_registry:
                        type: object
                        additionalProperties:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              argus:
                                type: object
                                  properties:
                                    argu_name:
                                      type: string
                                    argus_annotation:
                                      type: string
                                    argus_default:
                                      type: string
                              return_annotation:
                                type: string
                              comment:
                                type: string
        '501':
          description: 同步失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /sync/file/directory:
    get:
      tags:
        - 同步
      summary: 请求同步用户文件目录
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      file_directory:
                        type: object
                        additionalProperties:
                          type: array
                          items:
                            oneOf:
                              - type: string
                              - type: object
        '501':
          description: 同步失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /sync/file/config:
    get:
      tags:
        - 同步
      summary: 请求同步配置文件
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      configuration:
                        type: object
        '501':
          description: 同步失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    /file/config:
    patch:
      tags:
        - 用户修改配置
      summary: 发送修改后的配置表单
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                configuration:
                  type: object
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /file:
    post:
      tags:
        - 用户文件操作
      summary: 创建文件
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
    patch:
      tags:
        - 用户文件操作
      summary: 用户修改文件
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: 文件路径
                content:
                  type: string
                  description: 文件内容
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '501':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
    get:
      tags:
        - 用户文件操作
      summary: 用户查看文件
      security:
        - bearerAuth: ['read']
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: object
            properties:
              file_path:
                type: string
          description: 文件路径
      responses:
        '200':
          description: 确认
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      content:
                        type: string
        '404':
          description: 文件不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /file/user/file-name:
    put:
      tags:
        - 用户文件操作
      summary: 重命名用户文件
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_file_path:
                  type: string
                old_file_path:
                  type: string
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /file/user:
    delete:
      tags:
        - 用户文件操作
      summary: 用户删除用户文件
      security:
        - bearerAuth: ['write']
      parameters:
        - in: query
          name: file_path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /misson:
    get:
        tags:
          - 获取任务状态
        summary: 基于websocket连接获取任务状态
        security:
          - bearerAuth: ['read']
        responses:
          '200':
            description: 确认
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                    data:
                      type: object
                      additionalProperties:
                        type: object
          '500':
            description: 服务器错误
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
    post:
      tags:
        - 执行任务
      summary: 基于websocket连接发送任务信息
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:  # 项目名称
                type: object
                additionalProperties:   # 任务名称
                  type: object
                  properties:
                    STRATEGY_QUEUE:
                      type: array
                      items:
                        type: object
                        required: [ID, FUNC, ARGS]
                        properties:
                          ID:
                            type: string
                          FUNC:
                            type: string
                          ARGS:
                            type: object
                            additionalProperties: 
                              type: string
                    ITER:
                      type: boolean
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    additionalProperties:
                      type: object
                    
        '500':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
    delete:
      tags:
        - 停止正在运行的任务或删除等待运行的任务
      summary: 基于websocket连接发送任务信息
      security:
        - bearerAuth: ['write']
      parameters:
        - in: query
          name: misson_name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /monitor:
    get:
      tags:
        - 监测用户机系统信息
      summary: 获取状态信息，允许有空值
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      CPU:
                        type: object
                        properties:
                          load:
                            type: string
                          temperature:
                            type: string
                          power:
                            type: string
                      RAM:
                        type: object
                        properties:
                          load:
                            type: string
                      GPU:
                        type: object
                        properties:
                          load:
                            type: string
                          temperature:
                            type: string
                          power:
                            type: string
                      HDD:
                        type: object
                        properties:
                          load:
                            type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /scene/{sceneId}:
    parameters:
      - in: path
        name: sceneId
        required: true
        schema:
          type: string
    post:
      summary: Save current scene
      security:
        - bearerAuth: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectScene'
      responses:
        '200':
          description: Scene saved successfully
    get:
      summary: Restore project scene
      security:
        - bearerAuth: ['read']
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectScene'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      flows:
        authorizationCode:
          authorizationUrl: https://auth.operationend.我是占位符.com/oauth/authorize
          tokenUrl: https://auth.operationend.我是占位符.com/oauth/token
          scopes:   # 精简了
            read:   读权
            write:  写权

  schemas:
    UserRegistration:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string

    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    AuthToken:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer

    ProjectScene:
      type: object

    Error:
      type: object
      properties:
        message:
          type: string