openapi: 3.0.0
info:
  title: 管理控制 API
  version: 0.9.5
  description: 为高级模型用户设计的 CV 模型应用管理平台 API

servers:
  - url: https://api.managementend.example.com/v1

tags:
  - name: 同步
    description: 用于同步各种数据的端点
  - name: 配置
    description: 用于管理用户配置的端点
  - name: 文件操作
    description: 用于文件和目录管理的端点
  - name: 任务管理
    description: 用于管理和监控任务的端点
  - name: 系统监控
    description: 用于监控系统资源的端点

paths:
  /sync/file/strategy:
    get:
      tags:
        - 同步
      summary: 请求同步策略注册表
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StrategyRegistryResponse'
        '501':
          $ref: '#/components/responses/ErrorResponse'
          
  /sync/file/config:
    get:
      tags:
        - 同步
      summary: 请求同步配置文件
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationResponse'
        '501':
          $ref: '#/components/responses/ErrorResponse'
          
  /sync/file/directory:
    get:
      tags:
        - 同步
      summary: 请求同步用户文件目录
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectoryResponse'
        '501':
          $ref: '#/components/responses/ErrorResponse'
      
  /file/config:
    patch:
      tags:
        - 配置
      summary: 发送修改后的配置表单
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ConfigurationRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  /file:
    post:
      tags:
        - 文件操作
      summary: 创建文件或文件夹
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileCreationRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
          
    patch:
      tags:
        - 文件操作
      summary: 修改文件内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileModificationRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '501':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
          
    get:
      tags:
        - 文件操作
      summary: 查看文件内容
      parameters:
        - name: file_path
          in: query
          required: true
          schema:
            type: string
          description: 文件路径
      responses:
        '200':
          description: 成功获取文件内容
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileContentResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
          
  /file/user/file-name:
    put:
      tags:
        - 文件操作
      summary: 重命名用户文件
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileRenameRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
          
  /file/user:
    delete:
      tags:
        - 文件操作
      summary: 删除用户文件
      parameters:
        - in: query
          name: file_path
          schema:
            type: string
          required: true
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  
  /mission:
    get:
      tags:
        - 任务管理
      summary: 通过 WebSocket 连接获取任务状态
      responses:
        '200':
          description: 成功获取任务状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionStatusResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

    post:
      tags:
        - 任务管理
      summary: 通过 WebSocket 连接发送任务信息
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MissionRequest'
      responses:
        '200':
          description: 成功发送任务信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  
    delete:
      tags:
        - 任务管理
      summary: 停止运行中的任务或删除等待中的任务
      parameters:
        - in: query
          name: mission_name
          schema:
            type: string
          required: true
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  
  /monitor:
    get:
      tags:
        - 系统监控
      summary: 获取系统状态信息（允许空值）
      responses:
        '200':
          description: 成功获取系统状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatusResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

components:
  schemas:
    StrategyRegistryResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            strategy_registry:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/StrategyInfo'

    StrategyInfo:
      type: object
      additionalProperties:
        type: object
        properties:
          argus:
            type: object
            properties:
              argu_name:
                type: string
              argus_annotation:
                type: string
              argus_default:
                type: string
          return_annotation:
            type: string
          comment:
            type: string

    ConfigurationResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            configuration:
              type: object
              additionalProperties: true

    DirectoryResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            file_directory:
              type: object
              additionalProperties:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: object

    ConfigurationRequest:
      type: object
      properties:
        project_name:
          type: string
        content:
          type: object
          additionalProperties: true
        

    FileCreationRequest:
      type: object
      properties:
        path:
          type: string

    FileModificationRequest:
      type: object
      properties:
        file_path:
          type: string
          description: 文件路径
        content:
          type: string
          description: 文件内容

    FileContentResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            content:
              type: string

    FileRenameRequest:
      type: object
      properties:
        new_file_path:
          type: string
        old_file_path:
          type: string

    MissionStatusResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          additionalProperties:
            type: object

    MissionRequest:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: object
          properties:
            STRATEGY_QUEUE:
              type: array
              items:
                type: object
                required: [ID, FUNC, ARGS]
                properties:
                  ID:
                    type: string
                  FUNC:
                    type: string
                  ARGS:
                    type: object
                    additionalProperties: 
                      type: string
            ITER:
              type: boolean

    MissionResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          additionalProperties:
            type: object

    SystemStatusResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            CPU:
              type: object
              properties:
                load:
                  type: string
                temperature:
                  type: string
                power:
                  type: string
            RAM:
              type: object
              properties:
                load:
                  type: string
            GPU:
              type: object
              properties:
                load:
                  type: string
                temperature:
                  type: string
                power:
                  type: string
            HDD:
              type: object
              properties:
                load:
                  type: string

  responses:
    SuccessResponse:
      description: 操作成功
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    ErrorResponse:
      description: 发生错误
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    NotFoundResponse:
      description: 未找到资源
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
