openapi: 3.0.0
info:
  title: 管理层主控端 API
  version: 0.9.5
externalDocs:
  description: 面向高级模型用户的 CV 模型应用管理平台设计API
  url: https://api.managementend.我是占位符.com/v1
# tags:
#   - name: pet
#     description: Everything about your Pets
#     externalDocs:
#       description: Find out more
#       url: http://swagger.io
#   - name: store
#     description: Access to Petstore orders
#     externalDocs:
#       description: Find out more about our store
#       url: http://swagger.io
#   - name: user
#     description: Operations about user
paths:
  /sync/file/strategy:
    get:
      tags:
        - 同步
      summary: 请求同步策略注册表
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      strategy_registry:
                        type: object
                        additionalProperties:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              argus:
                                type: object
                                  properties:
                                    argu_name:
                                      type: string
                                    argus_annotation:
                                      type: string
                                    argus_default:
                                      type: string
                              return_annotation:
                                type: string
                              comment:
                                type: string
        '501':
          description: 同步失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /sync/file/config:
    get:
      tags:
        - 同步
      summary: 请求同步配置文件
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      configuration:
                        type: object
        '501':
          description: 同步失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /sync/file/directory:
    get:
      tags:
        - 同步
      summary: 请求同步用户文件目录
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      file_directory:
                        type: object
                        additionalProperties:
                          type: array
                          items:
                            oneOf:
                              - type: string
                              - type: object
        '501':
          description: 同步失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
  /file/config:
    patch:
      tags:
        - 用户修改配置
      summary: 发送修改后的配置表单
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                configuration:
                  type: object
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /file:
    post:
      tags:
        - 用户文件操作
      summary: 创建文件或文件夹
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
    patch:
      tags:
        - 用户文件操作
      summary: 用户修改文件
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: 文件路径
                content:
                  type: string
                  description: 文件内容
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '501':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
    get:
      tags:
        - 用户文件操作
      summary: 用户查看文件
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: object
            properties:
              file_path:
                type: string
          description: 文件路径
      responses:
        '200':
          description: 确认
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      content:
                        type: string
        '404':
          description: 文件不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /file/user/file-name:
    put:
      tags:
        - 用户文件操作
      summary: 重命名用户文件
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_file_path:
                  type: string
                old_file_path:
                  type: string
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /file/user:
    delete:
      tags:
        - 用户文件操作
      summary: 用户删除用户文件
      parameters:
        - in: query
          name: file_path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /misson:
    get:
      tags:
        - 获取任务状态
      summary: 基于websocket连接获取任务状态
      responses:
        '200':
          description: 确认
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    additionalProperties:
                      type: object
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - 执行任务
      summary: 基于websocket连接发送任务信息
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:  # 项目名称
                type: object
                additionalProperties:   # 任务名称
                  type: object
                  properties:
                    STRATEGY_QUEUE:
                      type: array
                      items:
                        type: object
                        required: [ID, FUNC, ARGS]
                        properties:
                          ID:
                            type: string
                          FUNC:
                            type: string
                          ARGS:
                            type: object
                            additionalProperties: 
                              type: string
                    ITER:
                      type: boolean
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    additionalProperties:
                      type: object
                    
        '500':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
    delete:
      tags:
        - 停止正在运行的任务或删除等待运行的任务
      summary: 基于websocket连接发送任务信息
      parameters:
        - in: query
          name: misson_name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /monitor:
    get:
      tags:
        - 监测用户机系统信息
      summary: 获取状态信息，允许有空值
      responses:
        '200':
          description: 正确
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      CPU:
                        type: object
                        properties:
                          load:
                            type: string
                          temperature:
                            type: string
                          power:
                            type: string
                      RAM:
                        type: object
                        properties:
                          load:
                            type: string
                      GPU:
                        type: object
                        properties:
                          load:
                            type: string
                          temperature:
                            type: string
                          power:
                            type: string
                      HDD:
                        type: object
                        properties:
                          load:
                            type: string
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string